---
- shell:
    rpm -q httpd
  register: rpm_check
  failed_when: rpm_check.rc == 1
- block:
    - get_url:
        url: "{{ https_uri }}"
        dest: /etc/httpd/conf.d/
    - file:
        path: /etc/httpd/conf.d/ssl
        state: directory
        mode: 0755
    - file:
        path: /var/www/html/logs
        state: directory
        mode: 0755
    - stat:
        path: /etc/httpd/conf.d/ssl.conf
      register: ssl_file
    - shell:
        mv /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.bak
      when: ssl_file.stat.exists
    - unarchive:
        src: "{{ ssl_uri }}" 
        dest: /etc/httpd/conf.d/ssl/
        copy: false
      notify:
        - restart_services
    - copy:
        content: "{{ ansible_fqdn }} ({{ ansible_default_ipv4['address'] }}) has been customized by Ansible\n"
        dest: /var/www/html/index.html
  when: rpm_check.rc == 0
