---
- hosts: webservers
  tasks:
    - block:
      - include: install_packages.yml
        vars:
          memory: 256
          web_package: httpd
          ssl_package: mod_ssl
          web_service: httpd
      - include: configure_web.yml
        vars:
          https_uri: "http://materials.example.com/task_control/https.conf"
          ssl_uri: "http://materials.example.com/task_control/ssl.tar.gz"
      - include: configure_firewall.yml
        vars:
          fw_package: firewalld
          fw_service: firewalld
        tags: production
      rescue:
      - yum:
          name: httpd
          state: latest
        notify:
          - restart_services
      - debug:
          msg: "Failed to import and run all the tasks; installing the web server manually"
      always:
      - shell:
          cmd: "systemctl status httpd"
  handlers:
    - name: restart_services
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - httpd
        - firewalld
