---
- name: Install Apache and start the service
  hosts: webserver

  tasks:
    - name: Install the required package
      yum:
        name: "{{ ansible_local['custom']['general']['package'] }}"
        state: latest
    - name: Start the service
      service:
        name: "{{ ansible_local['custom']['general']['service'] }}"
        state: "{{ ansible_local['custom']['general']['state'] }}"
